name: job

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  job:
    name: job
    runs-on: actuated-arm64-2cpu-8gb
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        run: |
          docker run -i arm32v6/alpine uname -a

      -
        run: |
          docker run -i arm32v7/ubuntu uname -a


      


